In [7]:
import numpy as np
X_test=np.array([[1,2,3],[2,3,4],[3,5,6],[1,6,1]])
X_train=np.array([[11,-2,3],[2,-3,4],[3,5,6],[11,6,11],[0,2,10]])


num_test = X_test.shape[0]
num_train = X_train.shape[0]
dists = np.zeros((num_test, num_train))
for i in range(num_test):
    for j in range(num_train):
        #slice_train=X_train[j:j+1,:]
        #slice_test=X_test[i:i+1,:]
        #dists[i,j]=np.sqrt(np.sum(np.power(slice_train-slice_test,2)))
        #dists[i][j]=np.sqrt(np.sum(np.power(X_test[i]-X_train[j],2)))
        dists[i][j]=np.sum(abs(X_test[i]-X_train[j]))
        pass
print(dists)
"""
sqrt((X[i][j]-Y[i][j])^2)=sqrt(X[i][j]^2+Y[i][j]^2-2*X[i][j]Y[i][j])

"""

[[14.  7.  8. 22.  8.]
 [15.  6.  5. 19.  9.]
 [18. 11.  0. 14. 10.]
 [20. 13.  8. 20. 14.]]
